/**
 * Export utilities — PDF, SRT, JSON, Image
 */

import type { AnalysisResult } from '../App'

/**
 * Export analysis as JSON file download.
 */
export function exportAsJson(analysis: AnalysisResult): void {
    const data = JSON.stringify(analysis, null, 2)
    downloadBlob(data, 'application/json', `vidiq-analysis-${Date.now()}.json`)
}

/**
 * Export analysis as plain text.
 */
export function exportAsText(analysis: AnalysisResult): string {
    return [
        `🎬 ${analysis.title}`,
        `Duration: ${analysis.duration}s | Scenes: ${analysis.totalScenes} | Objects: ${analysis.objectsDetected}`,
        `Model: ${analysis.model}`,
        '',
        analysis.summary,
        '',
        '━━━ Scene Timeline ━━━',
        '',
        ...analysis.scenes.map((s, i) =>
            `[${s.startTime}-${s.endTime}] #${i + 1} ${s.title}\n${s.description}` +
            (s.objects?.length ? `\nObjects: ${s.objects.join(', ')}` : '') +
            (s.actions?.length ? `\nActions: ${s.actions.join(', ')}` : '') +
            '\n'
        ),
        '',
        `Generated by VidIQ — vidiq.app`,
    ].join('\n')
}

/**
 * Generate SRT subtitle format from scenes.
 */
export function exportAsSrt(analysis: AnalysisResult): void {
    const srt = analysis.scenes.map((scene, i) => {
        const start = timeToSrt(scene.startTime)
        const end = timeToSrt(scene.endTime)
        return `${i + 1}\n${start} --> ${end}\n${scene.title}\n${scene.description}\n`
    }).join('\n')

    downloadBlob(srt, 'text/srt', `vidiq-subtitles-${Date.now()}.srt`)
}

/**
 * Export as PDF using browser print API.
 */
export function exportAsPdf(analysis: AnalysisResult): void {
    const html = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Inter', system-ui, sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; }
        h1 { font-size: 1.5rem; margin-bottom: 8px; }
        .summary { color: #555; margin-bottom: 24px; line-height: 1.6; }
        .stats { display: flex; gap: 24px; margin-bottom: 24px; padding: 12px 0; border-top: 1px solid #eee; border-bottom: 1px solid #eee; }
        .stat { font-size: 0.85rem; }
        .stat strong { color: #06B6D4; }
        .scene { margin-bottom: 16px; padding: 12px; border-left: 3px solid #06B6D4; background: #f8f9fa; border-radius: 4px; }
        .scene-time { font-family: monospace; color: #06B6D4; font-weight: 600; font-size: 0.85rem; }
        .scene-title { font-weight: 600; margin: 4px 0; }
        .scene-desc { color: #555; font-size: 0.9rem; line-height: 1.5; }
        .tags { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 6px; }
        .tag { background: #e0f7fa; color: #00838f; padding: 2px 8px; border-radius: 12px; font-size: 0.75rem; }
        .footer { margin-top: 32px; text-align: center; color: #999; font-size: 0.8rem; }
    </style>
</head>
<body>
    <h1>🎬 ${escapeHtml(analysis.title)}</h1>
    <div class="stats">
        <div class="stat"><strong>${analysis.duration}s</strong> Duration</div>
        <div class="stat"><strong>${analysis.totalScenes}</strong> Scenes</div>
        <div class="stat"><strong>${analysis.objectsDetected}</strong> Objects</div>
        <div class="stat"><strong>${analysis.model}</strong></div>
    </div>
    <div class="summary">${escapeHtml(analysis.summary)}</div>
    ${analysis.scenes.map((s, i) => `
    <div class="scene">
        <div class="scene-time">${escapeHtml(s.startTime)} — ${escapeHtml(s.endTime)}</div>
        <div class="scene-title">#${i + 1} ${escapeHtml(s.title)}</div>
        <div class="scene-desc">${escapeHtml(s.description)}</div>
        ${s.objects?.length ? `<div class="tags">${s.objects.map(o => `<span class="tag">${escapeHtml(o)}</span>`).join('')}</div>` : ''}
    </div>
    `).join('')}
    <div class="footer">Generated by VidIQ — vidiq.app</div>
</body>
</html>`

    const printWindow = window.open('', '_blank')
    if (printWindow) {
        printWindow.document.write(html)
        printWindow.document.close()
        setTimeout(() => printWindow.print(), 500)
    }
}

/**
 * Export analysis as image using html2canvas.
 */
export async function exportAsImage(elementId: string): Promise<void> {
    try {
        const { default: html2canvas } = await import('html2canvas')
        const element = document.getElementById(elementId)
        if (!element) return

        const canvas = await html2canvas(element, {
            backgroundColor: '#0A0A0F',
            scale: 2,
        })

        const link = document.createElement('a')
        link.download = `vidiq-analysis-${Date.now()}.png`
        link.href = canvas.toDataURL('image/png')
        link.click()
    } catch (err) {
        console.error('html2canvas export failed:', err)
    }
}

// ─── Helpers ────────────────────────────────────────────

function downloadBlob(content: string, mimeType: string, filename: string): void {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
}

function timeToSrt(mmss: string): string {
    const parts = mmss.split(':')
    if (parts.length === 2) {
        return `00:${parts[0].padStart(2, '0')}:${parts[1].padStart(2, '0')},000`
    }
    return `00:${mmss},000`
}

function escapeHtml(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
}

/**
 * Copy structured analysis text to clipboard.
 */
export function copyAnalysisText(analysis: AnalysisResult): void {
    const text = exportAsText(analysis)
    navigator.clipboard.writeText(text)
}

/**
 * Generate an embeddable iframe code snippet.
 */
export function generateEmbedCode(analysisId: string): string {
    return `<iframe src="https://vidiq.app/analysis/${analysisId}?embed=true" width="100%" height="600" frameborder="0" style="border-radius: 12px;"></iframe>`
}
