import { useState } from 'react'
import { ChevronDown, ChevronUp } from 'lucide-react'

const FAQS = [
    {
        q: "What video formats are supported?",
        a: "VidIQ supports MP4, MOV, WebM, and AVI files up to 100MB. You can also paste any YouTube URL for analysis."
    },
    {
        q: "How does the AI analysis work?",
        a: "We sample your video at 4 frames per second, then send those frames to NVIDIA's vision AI models (like Cosmos Reason 2). The AI uses chain-of-thought reasoning to understand what's physically happening in each scene, not just what's visible."
    },
    {
        q: "Is my video stored?",
        a: "Videos are stored temporarily for processing and auto-deleted after 30 days. Analysis text is retained in your history. You can delete all your data at any time from Settings."
    },
    {
        q: "What's the difference between Free and Premium?",
        a: "Free gives you 3 analyses per day for videos up to 30 seconds. Premium unlocks unlimited analyses, videos up to 10 minutes, custom prompts, multi-model comparison, and export options."
    },
    {
        q: "Can I use custom prompts?",
        a: "Yes! Premium users can add custom instructions like 'Focus on the cooking techniques' or 'Track the red car throughout.' The AI will tailor its analysis to your specific request."
    },
    {
        q: "How accurate is the analysis?",
        a: "AI analysis is generated by machine learning models and may not be 100% accurate. It's best used as a tool to quickly understand video content, not as a definitive source of truth."
    },
]

function HelpPage() {
    const [openIndex, setOpenIndex] = useState<number | null>(null)

    return (
        <div style={{ maxWidth: 700, margin: '0 auto' }}>
            <h2 style={{ marginBottom: 'var(--space-sm)' }}>❓ Help & FAQ</h2>
            <p className="text-secondary" style={{ marginBottom: 'var(--space-xl)' }}>
                Common questions about VidIQ
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-sm)' }}>
                {FAQS.map((faq, i) => (
                    <div
                        key={i}
                        className="card"
                        style={{ cursor: 'pointer' }}
                        onClick={() => setOpenIndex(openIndex === i ? null : i)}
                    >
                        <div className="flex items-center justify-between">
                            <h4 style={{ fontSize: '0.95rem', fontWeight: 600 }}>{faq.q}</h4>
                            {openIndex === i ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                        </div>
                        {openIndex === i && (
                            <p className="text-secondary" style={{ marginTop: 'var(--space-md)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                                {faq.a}
                            </p>
                        )}
                    </div>
                ))}
            </div>

            <div className="text-center" style={{ marginTop: 'var(--space-2xl)' }}>
                <p className="text-muted">
                    Still have questions? Email us at{' '}
                    <a href="mailto:support@vidiq.app">support@vidiq.app</a>
                </p>
            </div>
        </div>
    )
}

export default HelpPage
