export default function TermsPage() {
    return (
        <div className="legal-page">
            <h1>Terms of Service</h1>
            <p className="legal-page__updated">Last updated: February 2026</p>

            <section className="legal-section">
                <h2>1. Acceptance of Terms</h2>
                <p>
                    By accessing or using VidIQ ("the Service"), you agree to be bound by these Terms of Service.
                    If you do not agree, do not use the Service.
                </p>
            </section>

            <section className="legal-section">
                <h2>2. Description of Service</h2>
                <p>
                    VidIQ is an AI-powered video analysis platform that generates timestamped scene breakdowns,
                    object detection, and summaries using NVIDIA Vision Language Models. Analysis results are generated
                    dynamically and may vary between sessions.
                </p>
            </section>

            <section className="legal-section">
                <h2>3. User Accounts</h2>
                <p>
                    You must create an account to use certain features. You are responsible for maintaining
                    the confidentiality of your account credentials and for all activities under your account.
                </p>
            </section>

            <section className="legal-section">
                <h2>4. Subscriptions & Billing</h2>
                <p>
                    Paid subscriptions are billed monthly through Stripe. You may cancel at any time through
                    your account settings. Cancellation takes effect at the end of the current billing period.
                    No refunds are provided for partial months. Credit top-ups are non-refundable.
                </p>
            </section>

            <section className="legal-section">
                <h2>5. AI-Generated Content</h2>
                <p>
                    All analysis content is generated by AI models. While we strive for accuracy, we do not
                    guarantee the correctness, completeness, or suitability of AI-generated analysis. Users should
                    verify critical information independently.
                </p>
            </section>

            <section className="legal-section">
                <h2>6. Acceptable Use</h2>
                <p>You agree not to:</p>
                <ul>
                    <li>Upload copyrighted content without authorization</li>
                    <li>Use the Service to analyze harmful, offensive, or illegal content</li>
                    <li>Attempt to circumvent usage limits or rate limiting</li>
                    <li>Automate access to the Service beyond normal use</li>
                    <li>Share account credentials with others</li>
                    <li>Reverse-engineer or scrape the Service</li>
                </ul>
            </section>

            <section className="legal-section">
                <h2>7. Intellectual Property</h2>
                <p>
                    AI-generated analysis results created for your account are licensed to you for personal and
                    commercial use. The VidIQ platform, branding, and technology remain our intellectual property.
                </p>
            </section>

            <section className="legal-section">
                <h2>8. Limitation of Liability</h2>
                <p>
                    The Service is provided "as-is" without warranties. We are not liable for any damages arising
                    from the use or inability to use the Service, including reliance on AI-generated analysis.
                </p>
            </section>

            <section className="legal-section">
                <h2>9. Modifications</h2>
                <p>
                    We reserve the right to modify these terms at any time. Continued use after changes
                    constitutes acceptance. We will notify registered users of material changes via email.
                </p>
            </section>

            <section className="legal-section">
                <h2>10. Contact</h2>
                <p>
                    For questions about these Terms, contact us at <strong>support@vidiq.app</strong>.
                </p>
            </section>
        </div>
    )
}
