import { Link, useNavigate } from 'react-router-dom'
import { useConvexAuth } from 'convex/react'
import { useAuthActions } from '@convex-dev/auth/react'
import { Film, Menu, X } from 'lucide-react'
import { useState } from 'react'

function Layout({ children }: { children: React.ReactNode }) {
    const { isAuthenticated } = useConvexAuth()
    const { signOut } = useAuthActions()
    const navigate = useNavigate()
    const [mobileOpen, setMobileOpen] = useState(false)

    const handleSignOut = async () => {
        await signOut()
        navigate('/')
    }

    return (
        <div className="layout">
            <header className="header">
                <div className="header-inner">
                    <Link to="/" className="header-logo">
                        <Film size={24} className="header-logo-icon" style={{ color: 'var(--color-primary)' }} />
                        <span>VidIQ</span>
                    </Link>

                    {/* Mobile menu toggle */}
                    <button
                        className="btn-ghost"
                        onClick={() => setMobileOpen(!mobileOpen)}
                        style={{ display: 'none' }}
                        aria-label="Toggle menu"
                        id="mobile-menu-toggle"
                    >
                        {mobileOpen ? <X size={20} /> : <Menu size={20} />}
                    </button>

                    <nav className="header-nav">
                        <Link to="/">Analyze</Link>
                        <Link to="/pricing">Pricing</Link>
                        <Link to="/help">Help</Link>
                        {isAuthenticated ? (
                            <>
                                <Link to="/settings">Settings</Link>
                                <button className="btn btn-ghost btn-sm" onClick={handleSignOut}>
                                    Sign Out
                                </button>
                            </>
                        ) : (
                            <Link to="/login">
                                <button className="btn btn-primary btn-sm">Sign In</button>
                            </Link>
                        )}
                    </nav>
                </div>
            </header>

            <main className="layout-content">
                {children}
            </main>

            <footer className="footer">
                <p>
                    © {new Date().getFullYear()} VidIQ — Timestamped Video Intelligence •{' '}
                    <a href="/help">Help</a> • <a href="/pricing">Pricing</a>
                </p>
                <p style={{ marginTop: 4, fontSize: '0.75rem' }}>
                    AI analysis may not be 100% accurate. Results are generated by machine learning models.
                </p>
            </footer>
        </div>
    )
}

export default Layout
